name: Pipeline testes - The Test Tibe Porto

on: 
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * 1'  
             
jobs:
  Testes_API:
      # Maquina que irá ser executada o workflow
      runs-on: ubuntu-latest

      steps:
          # "Quem" ira clonar o repositorio para a execução
        - name: checkout
          uses: actions/checkout@v3

          # O que executara
        - name: Testes
          run: |
            docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests_api:/opt/robotframework/tests:Z \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest

        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports      

      
  Testes_Web:
        # Maquina que irá ser executada o workflow
        runs-on: ubuntu-latest

        # Indica a dependencia para correr o Job    
        needs: Testes_API

        steps:
            # "Quem" ira clonar o repositorio para a execução
          - name: checkout
            uses: actions/checkout@v3

            # O que executara
          - name: Testes
            run: |
              docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests_web:/opt/robotframework/tests:Z \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest

          - name: Upload reports
            uses: actions/upload-artifact@v1
            if: always()
            with:
              name: reports
              path: ${{ github.workspace }}/reports 